mongo:
  addresses:
    - localhost
  database: unknown
  server_id: nil
  auth:
    enabled: false
    username: username
    password: password
  connections: 10

tasks:
  thread-count: 10
bungee:
  fallback-server-name: fallback